<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="_SYS_COMP_FirstObject" Id="{c51e1415-84bf-474c-b3c8-ec8737582e96}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'call_after_init'}
FUNCTION_BLOCK FINAL _SYS_COMP_FirstObject EXTENDS Object
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//First object in global object list.
//DO NOT DELETE!!!]]></ST>
    </Implementation>
    <LineIds Name="_SYS_COMP_FirstObject">
      <LineId Id="9" Count="0" />
      <LineId Id="18" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>