<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="BaseParam" Id="{42da1c98-39da-4bba-9c49-2d1b281d511b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT BaseParam EXTENDS Object IMPLEMENTS I_Param
VAR
	_display: STRING := '0';
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Base Param object.
// _display should be used to extract data from the interface in string form. 
// For example to use with visu.

//Q variable should be used to access the data directly from FB.
//Each derivative of this funciton should have added Q variable of literal type.

//Each derivative of BaseParam has Quick_Change(value) to directly modify Q value.]]></ST>
    </Implementation>
    <Method Name="Change_Param" Id="{b2534efa-639f-4351-8c79-0b2100913693}">
      <Declaration><![CDATA[METHOD Change_Param
VAR_INPUT
	value	: STRING;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[//How string value should be translated to other data type]]></ST>
      </Implementation>
    </Method>
    <Property Name="display" Id="{03aaf4e1-7807-4d0f-bfec-738b9c6ff2bb}">
      <Declaration><![CDATA[PROPERTY display : STRING]]></Declaration>
      <Get Name="Get" Id="{53de3c53-9986-4265-90d7-e134a3cdb74f}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[display := _display;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="BaseParam">
      <LineId Id="24" Count="0" />
      <LineId Id="30" Count="1" />
      <LineId Id="35" Count="2" />
      <LineId Id="34" Count="0" />
      <LineId Id="33" Count="0" />
    </LineIds>
    <LineIds Name="BaseParam.Change_Param">
      <LineId Id="18" Count="0" />
    </LineIds>
    <LineIds Name="BaseParam.display.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>