<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="A" Id="{6af5d0de-e557-45e7-9f62-300c51773914}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'call_after_init'}
FUNCTION_BLOCK A EXTENDS Object
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	B1: B;
	B2: B;
	B3: B;

	tR: RealParam;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>